# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zp6fig2c7QQuShIq1WsKiUcOR6TrdyyS
"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# 
# st.title("Customer Churn Analysis")
# 
# df = pd.read_csv("/content/telco.csv")
# 
# st.subheader("Dataset Preview")
# st.dataframe(df.head())
# 
# st.subheader("Churn Distribution")
# fig, ax = plt.subplots()
# sns.countplot(x="Churn Label", data=df, ax=ax)
# st.pyplot(fig)
# 
# st.subheader("Churn vs Contract Type")
# fig, ax = plt.subplots()
# sns.countplot(x="Contract", hue="Churn Label", data=df, ax=ax)
# st.pyplot(fig)
# 
# st.subheader("Business Insights")
# st.write("""
# - Month-to-month customers churn more
# - Long-term contracts reduce churn
# - Contract type strongly impacts retention
# """)

!streamlit run app.py & npx localtunnel --port 8501

