# -*- coding: utf-8 -*-
"""customer_churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6Gg8-Kj-Gtks5e8UJi_p8CZ-XhAkNFQ

**Introduction**

# Customer Churn Analysis for a Subscription-Based Company

This project analyzes customer churn data to identify key factors
that cause customers to leave a telecom service and suggests
retention strategies based on data-driven insights.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# To display plots nicely
sns.set(style="whitegrid")

df = pd.read_csv('/content/telco.csv')

"""**Dataset Overview**"""

df.head()

df.shape

df.columns

"""**Data Cleaning**"""

df.isnull().sum()

#removed identifier, location-based, and post-churn columns to avoid data leakage
df.drop([
    'Churn Reason', 'Churn Category', 'Customer Status',
    'Churn Score', 'CLTV', 'Satisfaction Score','Customer ID', 'Zip Code', 'Latitude', 'Longitude', 'City', 'State', 'Country', 'Total Revenue','Total Refunds'
], axis=1, inplace=True)

df.shape

df.columns

df.isnull().sum()

#The missing values in Offer and Internet Type were not random. They represent customers without an active offer or internet service.
#Hence, missing values were replaced with ‘No Offer’ and ‘No Internet’ to preserve business meaning

df['Internet Type'] = df['Internet Type'].fillna('No Internet')
df['Offer'] = df['Offer'].fillna('No Offer')

df.isnull().sum()

"""**Exploratory Data Analysis (EDA)**"""

#EDA helps us understand why customers leave.📌 Example (real life)
#If I tell you:“Many customers are leaving”, Your next questions will be:
#Which customers?When?Why?   EDA answers these.

#How many customers stayed vs left? --> raw numbers
df['Churn Label'].value_counts()

# gives percentage --> Numbers depend on dataset size.Percentages are comparable and business-friendly.
df['Churn Label'].value_counts(normalize = True) * 100

#churn vs contract type. what kind of contract made customers leave the most?
sns.countplot(x ='Contract', hue ='Churn Label', data = df)
plt.title('Churn by Contract')
plt.show()

#chart analysis : The analysis shows that customers on month-to-month contracts have the highest churn,
#while customers on one-year and two-year contracts show significantly lower churn.
#This indicates that contract duration is a strong factor influencing customer retention.

#chart analysis : Customers who churn generally leave within the first year, whereas customers who do not churn tend to stay for several years.

sns.boxplot(x='Churn Label', y='Tenure in Months', data=df)
plt.title('Average Tenure by Churn')
plt.show()

#chart analysis : Customers with higher monthly charges are more likely to churn, while customers on lower-cost plans are more likely to stay.

sns.boxplot(x = 'Churn Label', y = 'Monthly Charge', data = df)
plt.title('Average Monthly Charge by Churn')
plt.show()

#chart analysis : Customers using Fiber Optic internet have the highest churn compared to other internet types.
sns.countplot(x = 'Internet Type', hue = 'Churn Label', data=df)
plt.title('Churn by Internet Type')
plt.show()

"""**Churn Analysis & Insights**

The analysis reveals clear patterns in customer churn behavior. Customers with shorter tenure are significantly more likely to churn, indicating that churn occurs primarily in the early stages of the customer lifecycle. This suggests that new customers are more vulnerable to leaving the service.

Monthly charges also play a major role in churn. Customers who churn tend to have higher average monthly charges compared to retained customers, indicating that pricing may be a key factor influencing customer dissatisfaction.

Additionally, Fiber Optic customers exhibit the highest churn compared to other internet types such as DSL and Cable. This may be attributed to higher pricing, increased service expectations, or competitive alternatives available in the Fiber Optic market.

Overall, the analysis suggests that early-stage customers on high-cost Fiber Optic plans are the most at risk of churning.

**Business Recommendations**

1. Focus on retaining new customers
Most churn happens in the early months. The company should pay more attention to new customers through better onboarding, early support, and regular check-ins during the initial period.

2. Review high-priced plans
Customers with higher monthly charges tend to churn more. Offering flexible pricing, discounts, or value-added benefits could help retain these customers.

3. Improve Fiber Optic customer experience
Fiber Optic users show higher churn compared to other internet types. This suggests a need to review pricing, service quality, and customer expectations for Fiber plans.

**Conclusion**

This project analyzed customer churn to identify key factors influencing customer retention. The analysis showed that churn is higher among customers with shorter tenure, higher monthly charges, and those using Fiber Optic internet services. Based on these insights, targeted retention strategies focusing on early customer engagement, pricing review, and service improvement can help reduce churn.
"""

!pip install streamlit

